title: "ln"
description: ""
author: "James Xu"
base_url: ""
url: "https://james-p-xu.github.io"
rss: false
social:
  linkedin: "https://www.linkedin.com/in/james-p-xu/"
  twitter: "https://twitter.com/jamespxu_"
  github: "https://github.com/james-p-xu"
